version: "3"
services:
  postgres:
    restart: always
    build: postgres
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432
  golang:
    build: golang
    container_name: golang
    privileged: true
    depends_on:
      - postgres
    volumes:
      - host_share:/share
    ports:
      - 8080:80
volumes:
  host_share:
    driver: local
    driver_opts:
      type: none
      device: /c/golang-container/share
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /c/golang-container/db
      o: bind
